import Head from 'next/head';

export default function Home() {
	return (
		<div className=''>
			<Head>
				<title>Home - Minimal Muslim </title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<section className='flex h-screen'>
				<video autoPlay loop muted className='absolute z-10 w-screen h-screen object-cover'>
					<source src='/video.mp4' type='video/mp4' />
				</video>
				<div className='text-gray-100 text-xl font-normal absolute z-10 pt-8 pl-16 inline-block pb-0 tracking-tight '>
					MNML
					<div className='m-0 pt-0 tracking-wide'>MSLM</div> <span className='flex-1 text-right items-end w-full'>لسلام عليكم|</span>
				</div>
				<div className='text-white z-10 absolute flex-1 text-center items-center p-72 font-bold text-5xl  tracking-wide  '>Design &nbsp; Faith &nbsp; Lifestyle</div>

<<<<<<< Updated upstream
				<div className='text-gray-100 border-red z-10 flex-1 text-right items-end w-full p-14 pt-32 pr-8 font-light text-xl '>
					<ul className=''>
						<li className='m-4 '>Insights</li>
						<li className='m-4'>Resources</li>
						<li className='m-4'>Initiatives</li>
						<li className='m-4'> Contact</li>
						<li className='m-4 hover:text-yellow-500 w-6 flex-1 text-right '>
							{' '}
							<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'>
								<path d='M504 256C504 119 393 8 256 8S8 119 8 256c0 123.78 90.69 226.38 209.25 245V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.28c-30.8 0-40.41 19.12-40.41 38.73V256h68.78l-11 71.69h-57.78V501C413.31 482.38 504 379.78 504 256z' />
							</svg>
						</li>
						<li className='m-4 hover:text-yellow-500 w-6'>
							{' '}
							<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 448 512'>
								<path d='M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z' />
							</svg>
						</li>
						<li className='m-4 hover:text-yellow-500 w-6'>
							<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 448 512'>
								<path d='M416 32H31.9C14.3 32 0 46.5 0 64.3v383.4C0 465.5 14.3 480 31.9 480H416c17.6 0 32-14.5 32-32.3V64.3c0-17.8-14.4-32.3-32-32.3zM135.4 416H69V202.2h66.5V416zm-33.2-243c-21.3 0-38.5-17.3-38.5-38.5S80.9 96 102.2 96c21.2 0 38.5 17.3 38.5 38.5 0 21.3-17.2 38.5-38.5 38.5zm282.1 243h-66.4V312c0-24.8-.5-56.7-34.5-56.7-34.6 0-39.9 27-39.9 54.9V416h-66.4V202.2h63.7v29.2h.9c8.9-16.8 30.6-34.5 62.9-34.5 67.2 0 79.7 44.3 79.7 101.9V416z' />
							</svg>
						</li>
					</ul>
				</div>
			</section>
			<section className='bg-gray-100 absolute z-10 pl-80 pr-80 pb-32 pt-32'>
				<div>
					<h1 className='italic text-2xl tracking-wide '>Bismillahir Rahmanir Raheem </h1>
					<h2 className='pt-6 pb-4 text-2xl tracking-wide'> MinimalMuslims journey began with Baseerah and we continue to strive on the path with Ihsaan!</h2>
					<div className='text-lg pt-4 tracking-wide text-gray-700 '>
						Minimal Muslim, a design movement that calls for re-interpretation/reformation of Islam-inspired Art, Architecture and Design, in a contemporary context.
						<p className='pt-8'>The objective is to develop a framework that helps create solutions for modern issues in accordance with Islamic principles while learning from the rich legacy of creative Muslim civilization</p>
					</div>
				</div>
			</section>
			<div className='h-screen w-full  '>
				<div>
					Insights
					<img src='2.jpg'></img>
				</div>
			</div>
			<div className='h-auto  '>
				<img src='1.jpg'></img>
			</div>

			<section className='h-auto bg-white relative z-10 flex-1 items-center text-center p-16 text-3xl tracking-wider pt-20 '>
				Featured by:
				<div className='flex flex-col text-center items-center  p-8 '> WhatsApp StartupIstanbul ca ThePrint TheQuint</div>
			</section>
			<section className='h-auto bg-black relative z-10 text-white flex-1 items-center text-center  '>
				<h1 className='text-2xl tracking-widest pt-24 pb-12 block'>TESTIMONIALS</h1>
				<h2>Refreshing meaningful creative designs that do a great job.</h2>
				<h3 className='text-gray-500 text p-6 text-sm tracking-wide'>Mazin Khan, The Milli Gazette</h3>
				<h2 className='block pt-6 pl-96 pr-96'>Liked the Idea very much, especially how the design of architecture impacts the behavior of occupants and how Islam inspired architecture can be modest, humble, and yet most modern.</h2>
				<h2 className='p-6'>Need of the hour for environment, Society, and humanity.</h2>
				<h3 className='text-gray-500 text p-6 text-sm tracking-wide'>Dr. Abrar Ahmed, JMI</h3>
				<h2 className='block pt-6 pl-96 pr-96'>Highly impressed with the creativity and thoughts behind your designs. The perfect fusion of classic and contemporary art. Keep up the good work. Best of luck!</h2>
				<h3 className='text-gray-500 text p-6 pb-24 text-sm tracking-wide'>Saad Ashraf</h3>
			</section>
			<section className='h-96 bg-gray-100  '>
				<h1 className='pt-20 pl-64'>Contact</h1>
				<h1 className='pt-6 pl-64 text-gray-700 text-sm'>contact@minimalmuslim.com</h1>
				<div className='block '>
					<form>
						<input
							type='email'
							id='email'
							className='bg-gray-100 border h-10 text-gray-900 text-sm inline-block w-64 mt-6 ml-64 p-4  dark:placeholder-gray-400 dark:text-white border-t-2 border-t-gray-300 border-b-2 border-b-black '
							placeholder='Enter your email here*'
							required></input>
						<button className='bg-gray-100 font-bold border-black border-2 text-black h-10 ml-2 inline-block hover:bg-yellow-500 hover:text-white w-24 hover:border-yellow-500 text-center items-center'>Join</button>
					</form>
				</div>
			</section>
			<footer>
				<div className='bg-black w-auto relative text-gray-300 text-center p-6 text-xs tracking-wider'>© 2021 by MINIMALMUSLIM.COM</div>
			</footer>
		</div>
	);
=======
        <div className="text-gray-100 border-red z-10 flex-1 text-right items-end w-full p-14 pt-32 pr-8 font-light text-xl ">
          <ul className="">
            <li className="m-4 ">Insights</li>
            <li className="m-4">Resources</li>
            <li className="m-4">Initiatives</li>
            <li className="m-4"> Contact</li>
            <li className="m-4 hover:text-yellow-500 w-6 flex-1 text-right ">
              {" "}
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                <path d="M504 256C504 119 393 8 256 8S8 119 8 256c0 123.78 90.69 226.38 209.25 245V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.28c-30.8 0-40.41 19.12-40.41 38.73V256h68.78l-11 71.69h-57.78V501C413.31 482.38 504 379.78 504 256z" />
              </svg>
            </li>
            <li className="m-4 hover:text-yellow-500 w-6">
              {" "}
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                <path d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z" />
              </svg>
            </li>
            <li className="m-4 hover:text-yellow-500 w-6">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                <path d="M416 32H31.9C14.3 32 0 46.5 0 64.3v383.4C0 465.5 14.3 480 31.9 480H416c17.6 0 32-14.5 32-32.3V64.3c0-17.8-14.4-32.3-32-32.3zM135.4 416H69V202.2h66.5V416zm-33.2-243c-21.3 0-38.5-17.3-38.5-38.5S80.9 96 102.2 96c21.2 0 38.5 17.3 38.5 38.5 0 21.3-17.2 38.5-38.5 38.5zm282.1 243h-66.4V312c0-24.8-.5-56.7-34.5-56.7-34.6 0-39.9 27-39.9 54.9V416h-66.4V202.2h63.7v29.2h.9c8.9-16.8 30.6-34.5 62.9-34.5 67.2 0 79.7 44.3 79.7 101.9V416z" />
              </svg>
            </li>
          </ul>
        </div>
      </section>
      <section className="h-auto bg-gray-100 absolute z-10">
        <div>
          <h1 className="pt-32 pl-80 italic text-2xl tracking-wide ">Bismillahir Rahmanir Raheem </h1>
          <h2 className="p-80 pt-6 pb-4 text-2xl tracking-wide">
            {" "}
            MinimalMuslims journey began with Baseerah and we continue to strive on the path with Ihsaan!
          </h2>
          <div className="text-lg pt-4 p-80 tracking-wide text-gray-700 ">
            Minimal Muslim, a design movement that calls for re-interpretation/reformation of Islam-inspired Art, Architecture and Design, in a contemporary
            context.
            <p className="pt-8">
              The objective is to develop a framework that helps create solutions for modern issues in accordance with Islamic principles while learning from
              the rich legacy of creative Muslim civilization
            </p>
          </div>
        </div>
      </section>
      <div className="h-screen w-screen object-cover  ">
        <img src="bk.jpg"></img>
      </div>

      <section className="h-auto bg-white relative z-10 flex-1 items-center text-center p-16 text-3xl tracking-wider pt-20 ">
        Featured by:
        <div className="flex flex-col text-center items-center  p-8 "> WhatsApp StartupIstanbul ca ThePrint TheQuint</div>
      </section>
      <section className="h-auto bg-black relative z-10 text-white flex-1 items-center text-center  ">
        <h1 className="text-2xl tracking-widest pt-24 pb-12 block">TESTIMONIALS</h1>
        <h2>Refreshing meaningful creative designs that do a great job.</h2>
        <h3 className="text-gray-500 text p-6 text-sm tracking-wide">Mazin Khan, The Milli Gazette</h3>
        <h2 className="block pt-6 pl-96 pr-96">
          Liked the Idea very much, especially how the design of architecture impacts the behavior of occupants and how Islam inspired architecture can be
          modest, humble, and yet most modern.
        </h2>
        <h2 className="p-6">Need of the hour for environment, Society, and humanity.</h2>
        <h3 className="text-gray-500 text p-6 text-sm tracking-wide">Dr. Abrar Ahmed, JMI</h3>
        <h2 className="block pt-6 pl-96 pr-96">
          Highly impressed with the creativity and thoughts behind your designs. The perfect fusion of classic and contemporary art. Keep up the good work. Best
          of luck!
        </h2>
        <h3 className="text-gray-500 text p-6 pb-24 text-sm tracking-wide">Saad Ashraf</h3>
      </section>
      <section className="h-96 bg-gray-100  ">
        <h1 className="pt-20 pl-64">Contact</h1>
        <h1 className="pt-6 pl-64 text-gray-700 text-sm">contact@minimalmuslim.com</h1>
        <div className="block ">
          <form>
            <input
              type="email"
              id="email"
              className="bg-gray-100 border h-10 text-gray-900 text-sm inline-block w-64 mt-6 ml-64 p-4  dark:placeholder-gray-400 dark:text-white border-t-2 border-t-gray-300 border-b-2 border-b-black "
              placeholder="Enter your email here*"
              required
            ></input>
            <button className="bg-gray-100 font-bold border-black border-2 text-black h-10 ml-2 inline-block hover:bg-yellow-500 hover:text-white w-24 hover:border-yellow-500 text-center items-center">
              Join
            </button>
          </form>
        </div>
      </section>
      <footer>
        <div className="bg-black w-auto relative text-gray-300 text-center p-6 text-xs tracking-wider">© 2021 by MINIMALMUSLIM.COM</div>
      </footer>
    </div>
  );
>>>>>>> Stashed changes
}
